# Generated by Django 4.2 on 2023-04-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
